name: CI

on:
  push:
    branches: [ "secret-ci" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Build the app
      run: npm run build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: .next
        
  detect-env-leaks:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build
    - name: Install Detect Secrets
      run: |
        pip3 install detect-secrets
    - name: Run Detect Secrets
      run: |
        detect-secrets scan --baseline .secrets.baseline
    - name: Verify Secrets Baseline
      run: |
        detect-secrets audit .secrets.baseline